# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-18 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('emailaddress', models.EmailField(max_length=300)),
            ],
        ),
    ]
